### ISSUE TITLE
plot_weather.py should automatically select y-axis limits

### ISSUE THREAD

**Issue by jamessynge** [panoptes/aag-weather#6]
The annual temperature range in Massachusetts (home of PAN006) is fairly large, especially when you include both ground and sky temps. For ambient, the range in the last 6 months has been about 100F. This is vastly different than the situation experienced by PAN001, which has a much lower annual range.

plot_weather.py uses limits in peas.yaml, such as:
```
    plot:
        amb_temp_limits: [-5, 35]
        cloudiness_limits: [-45, 5]
        wind_limits: [0, 75]
        rain_limits: [700, 3200]
        pwm_limits: [-5, 105]
```
I propose that these limits be auto computed from some time range (e.g. just the data in the daily plot, or the last week, etc.).
